// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl2Gwhmlq8ZStVT4R2eHDOYR9ymlNKG1g',
    appId: '1:547816512479:web:f70b1ffeb0b427007e426a',
    messagingSenderId: '547816512479',
    projectId: 'pictor-f2ee5',
    authDomain: 'pictor-f2ee5.firebaseapp.com',
    storageBucket: 'pictor-f2ee5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYHvST6FDJ-jZOnEyGm-P6NjoH2_AyUc4',
    appId: '1:547816512479:android:077500636f8798ba7e426a',
    messagingSenderId: '547816512479',
    projectId: 'pictor-f2ee5',
    storageBucket: 'pictor-f2ee5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUXNT6-l8uxSV1Lt-SiOL-QYbHm6uivLQ',
    appId: '1:547816512479:ios:65d5ae55acb991757e426a',
    messagingSenderId: '547816512479',
    projectId: 'pictor-f2ee5',
    storageBucket: 'pictor-f2ee5.appspot.com',
    iosBundleId: 'com.example.pictoria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUXNT6-l8uxSV1Lt-SiOL-QYbHm6uivLQ',
    appId: '1:547816512479:ios:48dfe2d32ac246287e426a',
    messagingSenderId: '547816512479',
    projectId: 'pictor-f2ee5',
    storageBucket: 'pictor-f2ee5.appspot.com',
    iosBundleId: 'com.example.pictoria.RunnerTests',
  );
}
